### PR TITLE
Include playbook url into mail

### PR DESCRIPTION
**Pull request by danielgoncharov**

### CODE REVIEW

**Review by JHK — COMMENTED** [review]
This would certainly do the trick, but I find it rather ugly.

How about modify the `SendNotification` method to accept a [template](https://pkg.go.dev/text/template) (if `nil` just use the text string) and provide the template as some kind of config. The config then can be set with an env variable.

**Comment by danielgoncharov** [comment]
I am a bit hesitant to modify the signature of SendNotification, as it is used not only in the AddUnknownClientId case, thus, I keep it as is and just extracted the the logic to the separate method.

@JHK please have a look whenever you have time

**Comment by danielgoncharov** [comment]
@JHK please have another look whenever you have time

**Review by JHK — APPROVED** [review]

**Comment by jojahner** [comment]
@danielgoncharov is this still something that you would like to get in?

**Comment by danielgoncharov** [comment]
Lets close it, we will deprecate the whole thing anyway soon

**Pull request closed without merging**
